"""Add batch verification system.

Revision ID: aa7340d35de7
Revises: bc01a12d3564
Create Date: 2026-09-29 02:25:15.259606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7340d35de7'
down_revision = 'bc01a12d3564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_code', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manufacture_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('lab_report_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('lab_report_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lab_report_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_batches_batch_id'))
        batch_op.create_index(batch_op.f('ix_batches_batch_code'), ['batch_code'], unique=True)
        batch_op.create_foreign_key('fk_batches_variant_id', 'product_variants', ['variant_id'], ['id'])
        batch_op.drop_column('verification_status')
        batch_op.drop_column('test_date')
        batch_op.drop_column('total_sugars_verified')
        batch_op.drop_column('total_sugars_unit')
        batch_op.drop_column('best_before_date')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('manufacturing_date')
        batch_op.drop_column('public_status')
        batch_op.drop_column('qr_image_path')
        batch_op.drop_column('qr_token')
        batch_op.drop_column('total_sugars_value')
        batch_op.drop_column('lab_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_sugars_value', sa.NUMERIC(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('qr_token', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('qr_image_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('public_status', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('manufacturing_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('best_before_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('total_sugars_unit', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('total_sugars_verified', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('test_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_batches_batch_code'))
        batch_op.create_index(batch_op.f('ix_batches_batch_id'), ['batch_id'], unique=1)
        batch_op.drop_column('lab_report_uploaded_at')
        batch_op.drop_column('lab_report_name')
        batch_op.drop_column('lab_report_url')
        batch_op.drop_column('status')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('manufacture_date')
        batch_op.drop_column('variant_id')
        batch_op.drop_column('batch_code')

    # ### end Alembic commands ###
